//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  daily: Daily;
  dailyConnection: DailyConnection;
  sprint: Sprint;
  sprintConnection: SprintConnection;
  blog: Blog;
  blogConnection: BlogConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDailyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDailyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DailyFilter>;
};


export type QuerySprintArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySprintConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SprintFilter>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};

export type DocumentFilter = {
  daily?: InputMaybe<DailyFilter>;
  sprint?: InputMaybe<SprintFilter>;
  blog?: InputMaybe<BlogFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Daily | Sprint | Blog | Folder;

export type DailyCover = {
  __typename?: 'DailyCover';
  image?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Daily = Node & Document & {
  __typename?: 'Daily';
  title: Scalars['String']['output'];
  number: Scalars['Float']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  date: Scalars['String']['output'];
  cover?: Maybe<DailyCover>;
  fmContentType?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DailyCoverFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DailyFilter = {
  title?: InputMaybe<StringFilter>;
  number?: InputMaybe<NumberFilter>;
  summary?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  cover?: InputMaybe<DailyCoverFilter>;
  fmContentType?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type DailyConnectionEdges = {
  __typename?: 'DailyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Daily>;
};

export type DailyConnection = Connection & {
  __typename?: 'DailyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DailyConnectionEdges>>>;
};

export type SprintCover = {
  __typename?: 'SprintCover';
  image?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Sprint = Node & Document & {
  __typename?: 'Sprint';
  title: Scalars['String']['output'];
  number: Scalars['Float']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  date: Scalars['String']['output'];
  cover?: Maybe<SprintCover>;
  fmContentType?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SprintCoverFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type SprintFilter = {
  title?: InputMaybe<StringFilter>;
  number?: InputMaybe<NumberFilter>;
  summary?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  cover?: InputMaybe<SprintCoverFilter>;
  fmContentType?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SprintConnectionEdges = {
  __typename?: 'SprintConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sprint>;
};

export type SprintConnection = Connection & {
  __typename?: 'SprintConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SprintConnectionEdges>>>;
};

export type BlogCover = {
  __typename?: 'BlogCover';
  image?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  date: Scalars['String']['output'];
  cover?: Maybe<BlogCover>;
  fmContentType?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BlogCoverFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  cover?: InputMaybe<BlogCoverFilter>;
  fmContentType?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateDaily: Daily;
  createDaily: Daily;
  updateSprint: Sprint;
  createSprint: Sprint;
  updateBlog: Blog;
  createBlog: Blog;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateDailyArgs = {
  relativePath: Scalars['String']['input'];
  params: DailyMutation;
};


export type MutationCreateDailyArgs = {
  relativePath: Scalars['String']['input'];
  params: DailyMutation;
};


export type MutationUpdateSprintArgs = {
  relativePath: Scalars['String']['input'];
  params: SprintMutation;
};


export type MutationCreateSprintArgs = {
  relativePath: Scalars['String']['input'];
  params: SprintMutation;
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};

export type DocumentUpdateMutation = {
  daily?: InputMaybe<DailyMutation>;
  sprint?: InputMaybe<SprintMutation>;
  blog?: InputMaybe<BlogMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  daily?: InputMaybe<DailyMutation>;
  sprint?: InputMaybe<SprintMutation>;
  blog?: InputMaybe<BlogMutation>;
};

export type DailyCoverMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type DailyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  number?: InputMaybe<Scalars['Float']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  date?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<DailyCoverMutation>;
  fmContentType?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SprintCoverMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type SprintMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  number?: InputMaybe<Scalars['Float']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  date?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<SprintCoverMutation>;
  fmContentType?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogCoverMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  date?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<BlogCoverMutation>;
  fmContentType?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type DailyPartsFragment = { __typename: 'Daily', title: string, number: number, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, cover?: { __typename: 'DailyCover', image?: string | null, alt?: string | null } | null };

export type SprintPartsFragment = { __typename: 'Sprint', title: string, number: number, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, cover?: { __typename: 'SprintCover', image?: string | null, alt?: string | null } | null };

export type BlogPartsFragment = { __typename: 'Blog', title: string, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, cover?: { __typename: 'BlogCover', image?: string | null, alt?: string | null } | null };

export type DailyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DailyQuery = { __typename?: 'Query', daily: { __typename: 'Daily', id: string, title: string, number: number, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'DailyCover', image?: string | null, alt?: string | null } | null } };

export type DailyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DailyFilter>;
}>;


export type DailyConnectionQuery = { __typename?: 'Query', dailyConnection: { __typename?: 'DailyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DailyConnectionEdges', cursor: string, node?: { __typename: 'Daily', id: string, title: string, number: number, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'DailyCover', image?: string | null, alt?: string | null } | null } | null } | null> | null } };

export type SprintQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SprintQuery = { __typename?: 'Query', sprint: { __typename: 'Sprint', id: string, title: string, number: number, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'SprintCover', image?: string | null, alt?: string | null } | null } };

export type SprintConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SprintFilter>;
}>;


export type SprintConnectionQuery = { __typename?: 'Query', sprintConnection: { __typename?: 'SprintConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SprintConnectionEdges', cursor: string, node?: { __typename: 'Sprint', id: string, title: string, number: number, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'SprintCover', image?: string | null, alt?: string | null } | null } | null } | null> | null } };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'BlogCover', image?: string | null, alt?: string | null } | null } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, summary?: string | null, tags?: Array<string | null> | null, date: string, fmContentType?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cover?: { __typename: 'BlogCover', image?: string | null, alt?: string | null } | null } | null } | null> | null } };

export const DailyPartsFragmentDoc = gql`
    fragment DailyParts on Daily {
  __typename
  title
  number
  summary
  tags
  date
  cover {
    __typename
    image
    alt
  }
  fmContentType
  body
}
    `;
export const SprintPartsFragmentDoc = gql`
    fragment SprintParts on Sprint {
  __typename
  title
  number
  summary
  tags
  date
  cover {
    __typename
    image
    alt
  }
  fmContentType
  body
}
    `;
export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  summary
  tags
  date
  cover {
    __typename
    image
    alt
  }
  fmContentType
  body
}
    `;
export const DailyDocument = gql`
    query daily($relativePath: String!) {
  daily(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DailyParts
  }
}
    ${DailyPartsFragmentDoc}`;
export const DailyConnectionDocument = gql`
    query dailyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DailyFilter) {
  dailyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DailyParts
      }
    }
  }
}
    ${DailyPartsFragmentDoc}`;
export const SprintDocument = gql`
    query sprint($relativePath: String!) {
  sprint(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SprintParts
  }
}
    ${SprintPartsFragmentDoc}`;
export const SprintConnectionDocument = gql`
    query sprintConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SprintFilter) {
  sprintConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SprintParts
      }
    }
  }
}
    ${SprintPartsFragmentDoc}`;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      daily(variables: DailyQueryVariables, options?: C): Promise<{data: DailyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DailyQueryVariables, query: string}> {
        return requester<{data: DailyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DailyQueryVariables, query: string}, DailyQueryVariables>(DailyDocument, variables, options);
      },
    dailyConnection(variables?: DailyConnectionQueryVariables, options?: C): Promise<{data: DailyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DailyConnectionQueryVariables, query: string}> {
        return requester<{data: DailyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DailyConnectionQueryVariables, query: string}, DailyConnectionQueryVariables>(DailyConnectionDocument, variables, options);
      },
    sprint(variables: SprintQueryVariables, options?: C): Promise<{data: SprintQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SprintQueryVariables, query: string}> {
        return requester<{data: SprintQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SprintQueryVariables, query: string}, SprintQueryVariables>(SprintDocument, variables, options);
      },
    sprintConnection(variables?: SprintConnectionQueryVariables, options?: C): Promise<{data: SprintConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SprintConnectionQueryVariables, query: string}> {
        return requester<{data: SprintConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SprintConnectionQueryVariables, query: string}, SprintConnectionQueryVariables>(SprintConnectionDocument, variables, options);
      },
    blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.1/content/460baf04-553c-49f3-8d02-61d7524da52b/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  